#!/bin/bash

THIS_DIR="`dirname $0`"
BN="`basename $0`"
if [ $# -lt 3 ]
then
  echo "$BN <out_gen_path> <deps_path> <c1> <c2> ..." >&2
  echo "(note: $BN must be run from project root)"    >&2
  exit 1
fi

# remember output dir
OUTPUT_DIR="$1"
shift
DEPS_PATH="$1"
shift

# go throught all files
for c in $*
do
  out="$OUTPUT_DIR/$c.mk"
  test -f "$out" && continue # skip if already exists
  "$THIS_DIR/getdeps" "$OUTPUT_DIR" "$DEPS_PATH" "$c"
done

# make default target
cat<<EOF > "$OUTPUT_DIR/_default_target_.mk"
.PHONY: all
all:: $*
EOF

exit 0

