#!/bin/bash

THIS_DIR="`dirname $0`"
BN="`basename $0`"
if [ $# -lt 5 ]
then
  echo "$BN <prj_root_path> <out_gen_path> <deps_path> <gen_libs_path> <c1> <c2> ..." >&2
  echo "(note: $BN must be run from project root)"    >&2
  exit 1
fi

# save project root
PRJ_ROOT_DIR="$1"
shift
# remember output dir
OUTPUT_DIR="$1"
shift
DEPS_PATH="$1"
shift
GEN_LIBS_PATH="$1"
shift

# go throught all files
for c in $*
do
  out="$OUTPUT_DIR/$c.mk"
  test -f "$out" && continue # skip if already exists
  "$THIS_DIR/getdeps" "$OUTPUT_DIR" "$DEPS_PATH" "$GEN_LIBS_PATH" "$c" || exit $?
done

# make default target
cat<<EOF > "$OUTPUT_DIR/_default_target_.mk"
.PHONY: all
all:: $*

BUILD_PROCESS_VERSION_TIMESTAMP:=\$(GEN_BASE_DIR)/build_process_version_check.ts
$*:: \$(BUILD_PROCESS_VERSION_TIMESTAMP)

# this code checks if build process' files didn't changed since initial
# build, and if so, inform user that (s)he should rebuild software
\$(BUILD_PROCESS_VERSION_TIMESTAMP): \$(wildcard \$(MAKEFILES_BASE_DIR)/*.mk)
\$(BUILD_PROCESS_VERSION_TIMESTAMP): \$(wildcard \$(MAKEFILES_BASE_DIR)/basic_mks/*)
\$(BUILD_PROCESS_VERSION_TIMESTAMP): \$(wildcard \$(MAKEFILES_COMMON_BASE_DIR)/*.mk)
\$(BUILD_PROCESS_VERSION_TIMESTAMP): \$(wildcard \$(MAKEFILES_PROFILES_BASE_DIR)/*.mk)
\$(BUILD_PROCESS_VERSION_TIMESTAMP): \$(wildcard \$(MAKEFILES_TOOLCHAINS_BASE_DIR)/*.mk)
\$(BUILD_PROCESS_VERSION_TIMESTAMP): \$(wildcard \$(SCRIPTS_BASE_DIR)/*)
	@if test -f "\$@" ; \
		then \
			echo "--------------------------------------------------------------------------" >&2 ; \
			echo "WARNING: BUILD PROCESS VERSION CHANGED SINCE LAST BUILD" >&2 ;\
			echo "WARNING: you're **STORNGLY** advised to remove current gen directory from:" >&2 ; \
			echo "WARNING: \$(GEN_BASE_DIR)" >&2 ; \
			echo "" >&2 ; \
			echo "if you understand what has happened and you are SURE this is false alarm" >&2 ; \
			echo "you can supprese this message by removing following file:" >&2 ; \
			echo "\$@" >&2 ; \
			echo "--------------------------------------------------------------------------" >&2 ; \
			false ; \
		else \
			echo "dependent files are: \$^" > "\$@" ; \
		fi
EOF

exit 0

